<?php

return [
    'trusted_source_domains' => [
        'medlineplus.gov',
        'nlm.nih.gov',
        'clinicaltables.nlm.nih.gov',
        'api.fda.gov',
        'open.fda.gov',
        'clinicaltrials.gov',
        'ghoapi.azureedge.net',
        'who.int',
    ],

    'source_fetch' => [
        'timeout_seconds' => 20,
        'medline_limit' => 4,
        'clinicaltables_limit' => 5,
        'max_output_sources' => 6,
    ],

    'openfda' => [
        'enabled' => true,
        'base_url' => 'https://api.fda.gov',
        'drug_term_limit' => 2,
        'label_limit' => 1,
        'event_reactions_limit' => 5,
        'drug_terms_map' => [
            'ибупроф' => 'ibuprofen',
            'парацет' => 'acetaminophen',
            'аспирин' => 'aspirin',
            'амоксиц' => 'amoxicillin',
            'азитромиц' => 'azithromycin',
            'метформин' => 'metformin',
            'омепраз' => 'omeprazole',
            'нимесул' => 'nimesulide',
            'кеторол' => 'ketorolac',
            'диклофен' => 'diclofenac',
            'ибуклин' => 'ibuprofen',
            'нурофен' => 'ibuprofen',
            'панадол' => 'acetaminophen',
            'тайленол' => 'acetaminophen',
            'анальгин' => 'metamizole',
            'дротавер' => 'drotaverine',
            'но-шпа' => 'drotaverine',
            'лоратадин' => 'loratadine',
            'цетиризин' => 'cetirizine',
            'левоцетир' => 'levocetirizine',
            'дезлоратад' => 'desloratadine',
            'супрастин' => 'chloropyramine',
            'амлодипин' => 'amlodipine',
            'лозартан' => 'losartan',
            'эналаприл' => 'enalapril',
            'бисопролол' => 'bisoprolol',
            'атенолол' => 'atenolol',
            'аторвастат' => 'atorvastatin',
            'розувастат' => 'rosuvastatin',
            'клопидогр' => 'clopidogrel',
            'варфарин' => 'warfarin',
            'ривароксаб' => 'rivaroxaban',
            'апиксабан' => 'apixaban',
            'инсулин' => 'insulin',
            'глибенклам' => 'glyburide',
            'сертралин' => 'sertraline',
            'эсциталопр' => 'escitalopram',
            'флуоксетин' => 'fluoxetine',
            'алпразолам' => 'alprazolam',
            'феназепам' => 'bromodihydrochlorophenylbenzodiazepine',
            'амитриптил' => 'amitriptyline',
            'левотирокс' => 'levothyroxine',
            'преднизолон' => 'prednisone',
            'дексаметазон' => 'dexamethasone',
            'сальбутамол' => 'salbutamol',
            'будесонид' => 'budesonide',
            'амброксол' => 'ambroxol',
            'ацетилцисте' => 'acetylcysteine',
            'мукалтин' => 'althaea officinalis',
            'цефтриаксон' => 'ceftriaxone',
            'цефуроксим' => 'cefuroxime',
            'ципрофлоксац' => 'ciprofloxacin',
            'доксициклин' => 'doxycycline',
            'метронидаз' => 'metronidazole',
            'флуконазол' => 'fluconazole',
            'ацикловир' => 'acyclovir',
            'осельтамивир' => 'oseltamivir',
            'смекта' => 'diosmectite',
            'лоперамид' => 'loperamide',
            'регидрон' => 'oral rehydration salts',
            'пенталгин' => 'acetaminophen',
            'цитрамон' => 'aspirin',
        ],
    ],

    'clinicaltrials' => [
        'enabled' => true,
        'base_url' => 'https://clinicaltrials.gov/api/v2',
        'studies_limit' => 3,
    ],

    'who_gho' => [
        'enabled' => true,
        'base_url' => 'https://ghoapi.azureedge.net/api',
        'indicators' => [
            'respiratory' => 'SA_0000001688',
            'cardiology' => 'NCD_CVD_30C',
            'neurology' => 'SA_0000001454',
            'gastro' => 'NCD_BMI_30A',
            'neutral' => 'NCD_BMI_30A',
        ],
    ],

    'translation' => [
        'ru_to_en' => [
            'кашл' => 'cough',
            'насморк' => 'runny nose',
            'горл' => 'sore throat',
            'температур' => 'fever',
            'озноб' => 'chills',
            'одыш' => 'shortness of breath',
            'боль в груди' => 'chest pain',
            'сердц' => 'heart palpitations',
            'тахикард' => 'tachycardia',
            'давлен' => 'blood pressure',
            'головокруж' => 'dizziness',
            'головн' => 'headache',
            'онемен' => 'numbness',
            'асимметр' => 'facial asymmetry',
            'реч' => 'speech difficulty',
            'тошнот' => 'nausea',
            'рвот' => 'vomiting',
            'диаре' => 'diarrhea',
            'боль в животе' => 'abdominal pain',
            'изжог' => 'heartburn',
            'сып' => 'rash',
            'кож' => 'skin symptoms',
            'зуд' => 'itching',
            'аллерг' => 'allergic reaction',
            'простуд' => 'common cold',
            'грипп' => 'influenza',
        ],
        'domain_terms' => [
            'respiratory' => ['respiratory symptoms'],
            'cardiology' => ['cardiology symptoms'],
            'neurology' => ['neurological symptoms'],
            'gastro' => ['digestive symptoms'],
        ],
    ],
];
